### ISSUE TITLE
Refactoring of AO transformations 

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#1]
AO transformations are in basisset.h, aomatrix.h, and threecenters.

**Comment by baumeier** [comment]
@JensWehner is that also cleaned up?

**Comment by JensWehner** [comment]
No, the issue still persists, The aocoulomb actually has its own transformation now. Reducing from threecenters and aomatrix to something smaller should be easy.

**Comment by JensWehner** [comment]
Still exists and cannot really be changed at the moment.
