### ISSUE TITLE
HDF Matrix Readin is flawed

### ISSUE THREAD

**Issue by JensWehner** [votca/xtp#130]
For quadratic matrices hdf5 read in and readout is accurate but columns and rows are exchanged. 
For non quadratic matrices the data is the read in incorrectly. 

It is also read out in the same incorrect way. So for checkpointing it is not problematic but for reading out the hdf5 file with python or so it is.  

Example is qpert from GW calculations

**Comment by JensWehner** [comment]
https://stackoverflow.com/questions/24116713/hdf5-rowmajor-or-colmajor

**Comment by JensWehner** [comment]
@felipeZ @NicoRenaud Do you guys have experience with that? According to my research we basically have to transpose the data by hand before we read them in or out...

**Comment by felipeZ** [comment]
I have built some [utilities for hdf5](https://github.com/SCM-NV/qmflows-namd/blob/master/nac/common.py#L68) and my package follows the `Row Major` convention as it is the case of scipy, see for instance the [scipy.linalg.eigh function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eigh.html). So, indeed I transpose the matrices after reading them.
It is a convention and I think it is ok to follow it, as long as you state that in the documentation.

**Comment by JensWehner** [comment]
@pmadhikar we have a lot of symmetric matrices, for which this is not necessary. But for some it is. I am not sure what to do?

a) before reading in make a copy and transpose it. Disadvantage we have to make a copy
b) transpose in place and read in. Disadvantage, we have to transpose it back afterwards
c) do a) or b) only for non symmetric matrices, more bookkeeping effort
d) change all eigen matrices to row major, which means rewriting quite some code.

**Comment by pmadhikar** [comment]
@JensWehner I think there is a trick that can be done to just write the matrices col major instead of row major. There shouldn't be a need to make copies or transposing in that case. It will need some preprocessing before reading/writing - but the bottleneck should always be disk io anyway so no biggie. 

Sorry, I'm also a bit confused. What do you mean by read in vs read out? Does read in mean write to hdf5 file?

**Comment by JensWehner** [comment]
yeah sorry read in was supposed to mean write out. That was terrible phrasing on my part.

**Comment by JensWehner** [comment]
Using column major in hdf5 would of course be the best. But I have not found any such thing.

**Comment by pmadhikar** [comment]
I've written some code that implements the solution we discussed. But I hesitate to say it's completely fixed without some further testing by someone else. @JensWehner ?

Let's test it some more before merging.

**Comment by JensWehner** [comment]
I tested it once and it works as advertised.
