### ISSUE TITLE
hdfview is broken on Ubuntu 18.04

### ISSUE THREAD

**Issue by JensWehner** [votca/xtp#133]
basically this:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853750

**Comment by pmadhikar** [comment]
According to that link hdfview should be compatible with hdf5 1.8. ubuntu 18.04 comes with 1.10 which is not backwards compatible, but it can be set to be in "1.8 mode". Which also removes some nice 1.10 features I think. But we don't need any of them afaik. 

So I will do that.

**Comment by pmadhikar** [comment]
The setting is done with setting the hdf5 access mode to version 1.8. The way to do this is by calling a special function like this: 

    H5::FileAccPropList::DEFAULT.setLibverBounds(H5F_LIBVER_EARLIEST,  HF5_LIBVER_18);

_However_ `HF5_LIBVER_18` becomes `HF5_LIBVER_V18` (`V18` vs `18`) in hdf5 1.10, which defeats the whole purpose of this function. So we need to do preproc tricks to see what the version is and use the correct identifier in the function call. 

The HDF5 group is filled with very nice people...

**Comment by pmadhikar** [comment]
As it turns out the above functionality is only available in hdf5 1.10.2 unbuntu 18.04 comes with 1.10.0. 

hdf5 1.8 already had it. 




D;

**Comment by JensWehner** [comment]
unbelieveable
