### ISSUE TITLE
QMMM writing of coordinates is broken

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#134]
Independent of qmpackage, no coordinates are written into the DFT package input files.

**Comment by JensWehner** [comment]
which branch?

**Comment by JensWehner** [comment]
is your segment.xyz a proper xyz file?

**Comment by baumeier** [comment]
development

**Comment by baumeier** [comment]
yes

**Comment by JensWehner** [comment]
okay

**Comment by JensWehner** [comment]
which packages did you try, most likely you missed a keyword:

"charge" in gaussian
"set bq background" in nwchem
"pointcharges" in orca

**Comment by baumeier** [comment]
nwchem and orca.
and what has charge to do with atom coordinates?

**Comment by JensWehner** [comment]
yeah, I agree. It is historical. At least it should throw a warning

**Comment by JensWehner** [comment]
So the reason seems to be:
qmpackage can either read the coordinates from a segment or an orbitals object, normally it does the latter. QMpackages only knows that it should read from the later if the keywords given above are specified

**Comment by baumeier** [comment]
I suggest we change that to a bool flag that is set by qmmm?
