### ISSUE TITLE
State identification in numerical forces

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#140]
- needed for gradients of excited states which are energetically close

- similar to QM/MM state following, could be overlap based or density matrix based

- for approximate spectra evaluation, add gradient mode that calculates all gradients (no extra effort, since spectrum is available in numerical grads for all states at the same time), but no opt, see @gtirimbo 's approach

**Comment by JensWehner** [comment]
point 1 and 2 are done by #152

**Comment by JensWehner** [comment]
@gtirimbo I need additional information about what has to be accomplished.

**Comment by JensWehner** [comment]
@baumeier still relevant?
