### ISSUE TITLE
Bug in the xyz reader

### ISSUE THREAD

**Issue by mbarbry** [votca/xtp#141]
Hi,

I found a small bug in the xyz reader (file `xtp/src/tools/Md2QmEngine.cc`, function `Md2QmEngine::getIntCoords`). The actual reader cannot handle correctly xyz file with comments in the second line. For example

    5
    Lattice="29.823 0.0 14.9115 0.0 29.823 14.9115 0.0 0.0 21.0881" Properties=species:S:1:pos:R:3 pbc="T T T"
    C      22.35000000      22.36000000      10.54000000 
    H      22.54000000      22.69000000      11.55000000 
    H      22.37000000      21.28000000      10.52000000 
    H      21.41000000      22.73000000      10.12000000 
    H      23.17000000      22.78000000       9.99000000

A simple solution could be to just ignore the second line since there is no need to read it. I implemented the correction in a fork https://github.com/mbarbry/xtp/commit/dbdbebdb35e490f5e633d6de418fb80d0575e197 Do you have some particular rules before that I open a merge request?

Best regards,
Marc Barbry

**Comment by junghans** [comment]
Yes, please open a pull request!

Ultimately we should switch to the xyz reader in csg!

**Comment by JensWehner** [comment]
I did not know, that there was another .xzy reader......

**Comment by junghans** [comment]
One... there are hundrets in xtp ;-)

The csg one is here: https://github.com/votca/csg/blob/master/src/libcsg/modules/io/xyzreader.cc

**Comment by JoshuaSBrown** [comment]
Great :). I'll fix this unless @mbarbry you want to give it a try? I can provide assistance.

**Comment by mbarbry** [comment]
I can give it a try.
If I understand, it would be to call the readxyz function from the csg module instead to have it implemented in the xtp one?

**Comment by JensWehner** [comment]
The problem is, that the csg reader is too specific with the topology object.
