### ISSUE TITLE
edft - issue with atoms coordinates

### ISSUE THREAD

**Issue by mbarbry** [votca/xtp#147]
I spotted a new problem, this time with the edft calculator. After updating the code, it seems that the positions of the atoms in a segment are not correctly resolved. When running the command

    xtp_parallel -o OPTIONFILES/edft.xml -e edft -f states.sql -j "write run"

somehow the positions of the atoms are set to `nan`. In the nwchem input,

    geometry noautoz noautosym
      C        -nan        -nan        -nan
      H        -nan        -nan        -nan
      H        -nan        -nan        -nan
      H        -nan        -nan        -nan
      H        -nan        -nan        -nan
    end

These calculations were working correctly before I updated Votca.

**Comment by JensWehner** [comment]
Branch tutorial fixes?

**Comment by JensWehner** [comment]
because that should not have that calculator anymore

**Comment by mbarbry** [comment]
both master and tutorial-fixes are concerned by this issue.
So the edft calculator will be removed in future releases?

What is then the way to get the transfer integrals between molecules?

**Comment by baumeier** [comment]
This is related to #101 - we had separate calculators for dft calculations (edft/idft) and for gwbse calculations (egwbse/igwbse) to get respective transfer integrals. But the functionality is very much identical with the gwbse versions obviously doing a little more - so to consolidate, there should now be a general eqm/iqm.

**Comment by mbarbry** [comment]
Trying with `eqm` instead of `edft` I get the same issue. The positions of the atoms are nan values. However, the nwchem inputs when running `qmmm` are correct.

**Comment by mbarbry** [comment]
I found out that the qmPos that are used in the converter between segments and orbitals (`QMInterface::Convert(std::vector<ctp::Segment* > segments)`) are all null in my states file


        sqlite3 states.sql "SELECT * FROM atoms"
    2500|0|0|2500|HB4|HB4|500|500|500|1|ALAB|4.38600015640259|0.386999994516373|2.23900008201599|1.0|H|5|0.0|0.0|0.0

If I use Pos parameter instead of qmPos in the converter, then the input files for nwchem are correctly written. Any idea why the qmPos are not correctly set? And what the difference between Pos and qmPos?

**Comment by baumeier** [comment]
IIRC, it had to do with the difference between the bare coordinates from MD and the ones after re-mapping them to optimized fragment structures. But it might also be largely esoteric reasons - which is I guess @JensWehner plans to drop one of them. And missed it there.
