### ISSUE TITLE
Refactor Atom Class

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/xtp#149]
I need feedback before I do this. I will be doing this by inheriting from the basebead

However, I have a few questions:
1. What is the Weight method referring to is this the same as the Mass?
2. I need a reminder of what these maps contain, I know we have discussed before:
// charge state of segment => partial charge                                   
  std::map<int, double> _Q;                                                      
  std::map<int, double>::iterator _q;                                            
  votca::tools::matrix _ptensor;
3. What is the ptensor, is this describing the orientation of the momentum?
4. How is the QM Id setup, is there a second atom object associated with the quantum chemistry optimized structure?

Q is the partial charge where you define singlet, triplet and excited states?

**Comment by baumeier** [comment]
No guarantees, so please anyone else call me out if I'm wrong:

> What is the Weight method referring to is this the same as the Mass?

Yeah, usually. Although I believe it doesn't *have* to be. I think the weight will be used to calculate the CoM of a fragment/segment for the mapping. There might be cases in which one might want to exclude certain atoms from the CoM, e.g., hydrogens. 

> // charge state of segment => partial charge
std::map<int, double> _Q;

As it says, it's the partial charge of the atom, as obtained from ESP fits. But there can be different charges depending on what state the molecule is in. I think the states are electron (int: -1), neutral (int: 0), hole (int: 1), singlet exciton (int: 2), triplet exciton (int: 3).  

> What is the ptensor, is this describing the orientation of the momentum?

Probably the atomic polarizibility tensor, as read from the *.mps file.

>  Is state the same thing as multiplicity?

State is the integer label of the electron, neutral, hole, singlet exciton, triplet exciton states as above.

**Comment by JoshuaSBrown** [comment]
@JensWehner and @gtirimbo if you guys have any input on this I would appreciate it.

**Comment by JoshuaSBrown** [comment]
So, I see that the qmatom makes a distinction between the nuclear charge and the partial charge, this is separate from the setQ and getQ methods in the normal atom class. 
```

   int getNuccharge() { return nuccharge-ecpcharge;}

   void setPartialcharge(double _q){partialcharge=_q;}
   const double & getPartialcharge() const { return partialcharge;}

```

**Comment by JensWehner** [comment]
I have not seen this, do not use polarsite, we have a cleanup version already in embedding branch called polarsite

**Comment by JensWehner** [comment]
I personally think, the atom object should have non of this information, ecp charge is purely interesting for QMAtoms

**Comment by baumeier** [comment]
What is the status of this issue?

**Comment by JoshuaSBrown** [comment]
I have not done anything with this since August, though the last time @JensWehner and I talked it was mentioned. From what I remember of our discussion there were three classes that had similar functionality but were used for distinctly different purposes: 
atom class - similar functionality to csg bead class
apolarsite class - takes care of the electro statics
qmatom class - quantum mechanical version of the atom
I cannot remember if we came to an strong consensus on how to separate the functionality to clean them up but I know that Jens has made small changes since then.

**Comment by JensWehner** [comment]
the issue will be dealt with in the elektrostatics branch

**Comment by JoshuaSBrown** [comment]
This was done in the electrostatics branch closing.
