### ISSUE TITLE
HDF5 orb file

### ISSUE THREAD

**Issue by JensWehner** [votca/xtp#15]
What savefile should contain

# of external charges
bool APEorNot
number of alpha electrons
number of beta electrons
alpha/beta MOs reordert in xtp
alpha/beta MOEnergies
qm_atoms
TotalGSEnergy
Basisset name and object
ECP name and object
Vxc
Functional name
frac of EXX
Original qmpackage name
GW pert energies
GW diag energies and states
GW aux basisset name and object
BSE S/T Energies
BSE S/T Coefficients
BSE S/T AR_Coefficients
BSE Hamiltionian parts

maybe:
Fragment pops
Transition dipoles

**Comment by pmadhikar** [comment]
Initial commit with dummy data and unit tests: 
f2674b808b617e307442a862437726ce97aad8d1

**Comment by pmadhikar** [comment]
Follow the code [here](https://github.com/votca/xtp/blob/9a249fd34615abcf790d5f0ecd3ddf1ed0ac0e7a/include/votca/xtp/orbitals.h#L869l) to see what data to write/read.

**Comment by pmadhikar** [comment]
We'll be writing the variables below.

### orbitals members
basis_set_size
occupied_levels
unoccupied_levels
number_of_electrons
mo_energies
mo_coefficients
_atoms, see qmatom members below
qm_energy
qm_package
self_energy
dftbasis
auxbasis
rpamin
rpamax
qpmin
qpmax
bse_vmin
bse_vmax
bse_cmin
bse_cmax
ScaHFX
bsetype
ECP
QPpert_energies
QPdiag_energies
QPdiag_coefficients
eh_d
eh_x
BSE_singlet_energies
BSE_singlet_coefficients
BSE_singlet_coefficients_AR
transition_dipoles
BSE_triplet_energies
BSE_triplet_coefficients

### qmatom members:
index
type
pos
nuccharge
ecpcharge
partialcharge

**Comment by pmadhikar** [comment]
HDF5 has been implemented, closing
