### ISSUE TITLE
xtp_run and xtp_parallel --list option does not appear to work

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/xtp#163]
Demonstrated on both master and development branches. 

```
xtp_run --list
Available XTP calculators: 
an error occurred:
basic_string::_M_construct null not valid
```

```
xtp_parallel --list
Available XTP calculators: 
an error occurred:
basic_string::_M_construct null not valid
```

**Comment by JensWehner** [comment]
Cannot reproduce it.

**Comment by JoshuaSBrown** [comment]
Hmm, let me recompile everything and see if that gets rid of the problem.

**Comment by JensWehner** [comment]
something in xtp_tools in load property from xml still leaks memory

**Comment by JoshuaSBrown** [comment]
Well, on recompilation I'm still getting this error too. So there is something fishy going on. I've already found a memory issue with table.h in tools, it's likely that there are more.

**Comment by JensWehner** [comment]
can you have a look if it persists after https://github.com/votca/tools/pull/74

**Comment by JensWehner** [comment]
I cannot reproduce it anywhere

**Comment by JensWehner** [comment]
does valgrind or so give more output. I need more info

**Comment by JoshuaSBrown** [comment]
No that's it. Valgrind does not find anything wrong.

**Comment by junghans** [comment]
Is this the xtp version of https://github.com/votca/ctp/issues/100!

**Comment by JensWehner** [comment]
yes that mqkes sense
