### ISSUE TITLE
hdf5 wrapper module

### ISSUE THREAD

**Issue by pmadhikar** [votca/xtp#171]
The wrapper should support easily reading in data form hdf5 files. The wrapper is specific to the xtp hdf5 structure. But it will be completely agnostic to what it contains. The user must not be required to use h5py at all. Although it should be possible to do so.

The structure will be based on the idea of a **Folder**, which is basically a group in hdf5 lingo.

 #### **Folder** Class
 This class knows what **Parameter** values and **Data** values it contains.
 - **Parameters** are any scalar quantities such as: ints, doubles, strings, characters. These are stored as attributes hdf5
 - **DataSets** are vector or matrix quantities. These are stored as datasets in hdf5. The wrapper will return a numpy array of the same shape as the dataset.

 It also knows how to access all of it's child **Folder**s.

 **Folder**s will **not support** writing data for now.

 **Folder**s will recursively generate and parse their child **Folder**s.

--------------------------

 #### **OrbReader** Class
 This class will just contain a **Folder** that accesses the root location(`"/"`).

@gtirimbo

**Comment by pmadhikar** [comment]
See branch [hd5-module](/votca/xtp/tree/hdf5-module)

**Comment by JensWehner** [comment]
I think because of the easy with which to use h5py this is not required anymore
