### ISSUE TITLE
Generating overview_stochastic.eps trigggers an internal error in inkscape on s390x

### ISSUE THREAD

**Issue by junghans** [votca/xtp#189]
When testing 1.5_rc1 on s390x, I get:
```
[ 89%] Generating fig/stochastic/overview_stochastic.eps
cd /builddir/build/BUILD/votca-1.5_rc1/s390x-redhat-linux-gnu/xtp/manual/fig/stochastic && /usr/bin/inkscape -f /builddir/build/BUILD/votca-1.5_rc1/xtp/manual/fig/stochastic/overview_stochastic.svg -E /builddir/build/BUILD/votca-1.5_rc1/s390x-redhat-linux-gnu/xtp/manual/fig/stochastic/overview_stochastic.eps
make[2]: Leaving directory '/builddir/build/BUILD/votca-1.5_rc1/s390x-redhat-linux-gnu'
BUILDSTDERR: terminate called after throwing an instance of 'std::logic_error'
BUILDSTDERR:   what():  basic_string::_M_construct null not valid
BUILDSTDERR: Emergency save activated!
BUILDSTDERR: Emergency save completed. Inkscape will close now.
BUILDSTDERR: If you can reproduce this crash, please file a bug at www.inkscape.org
BUILDSTDERR: with a detailed description of the steps leading to the crash, so we can fix it.
BUILDSTDERR: ** Message: 03:23:39.190: Error: Inkscape encountered an internal error and will close now.
```

**Comment by junghans** [comment]
This one is still valid! We should report this to Inkscape upstream.

**Comment by junghans** [comment]
https://bugs.launchpad.net/votca/+bug/1810425

**Comment by junghans** [comment]
The problem seems to be the length of the input (`-f` option) and output (`-E` option) path.

**Comment by crionez** [comment]
Fixing inkscape command line bug boils down to ugly CMaking? I would rather push eps figures to the manual repository. Also I do not have this platform installed to check if one can fix it in a different fashion.

**Comment by junghans** [comment]
Adding the eps files has the disadvantage that all users will have to download more data as the tarballs is bigger! I think the fix wasn’t that ugly....

**Comment by crionez** [comment]
If you have access to s390x, can you check if 
inkscape --file=<dir>/<file>.svg --export-eps=<dir>/<file>.eps
works? 
Or even put in parenthesis "<dir>/<file>.svg" and "<dir>/<file>.eps"
