### ISSUE TITLE
Gitlab CI improvements

### ISSUE THREAD

**Issue by junghans** [votca/xtp#210]
@JensWehner @JoshuaSBrown @baumeier, please list further GitLab CI improvement on this issue.

**Comment by baumeier** [comment]
@onurcaylak comments are welcome

**Comment by JensWehner** [comment]
We should activate the unittests as well

**Comment by junghans** [comment]
What unittests?

**Comment by baumeier** [comment]
As far as I can see, they all run by default.

**Comment by junghans** [comment]
Yes, there is a "make test" in there already!

**Comment by JensWehner** [comment]
okay I did not see that. Not my day.
