### ISSUE TITLE
library calls exit

### ISSUE THREAD

**Issue by junghans** [votca/xtp#220]
Rpmlint on openSUSE says:
```
libvotca_xtp5.x86_64: W: shared-lib-calls-exit /usr/lib64/libvotca_xtp.so.5 exit@GLIBC_2.2.5
This library package calls exit() or _exit(), probably in a non-fork()
context. Doing so from a library is strongly discouraged - when a library
function calls exit(), it prevents the calling program from handling the
error, reporting it to the user, closing files properly, and cleaning up any
state that the program has. It is preferred for the library to return an
actual error code and let the calling program decide how to handle the
situation.
```

**Comment by JensWehner** [comment]
is there more info?

**Comment by JensWehner** [comment]
i cannot find an exit() call

**Comment by baumeier** [comment]
There are a number if exit(1), e.g., in aodipole.cc

`if ( lmax_col > 4 ) {
            std::cerr << "Momentum transition dipoles only implemented for S,P,D,F,G functions in DFT basis!" << std::flush;
            exit(1);
        }`

**Comment by JoshuaSBrown** [comment]
aobasis.cc
202:        exit(1);

aoshell.cc
278:            exit(1);
281:            exit(1);
379:                        exit(1);

**Comment by baumeier** [comment]
Almost is all aomatrix cc's, aobasis, aoshell,

**Comment by JoshuaSBrown** [comment]
And in stable:
aobasis.cc
195:        exit(1);

fourcenter.cc
36:            exit(0);

threecenter_dft.cc
34:          exit(0);

**Comment by baumeier** [comment]
numerical_integration/sphere_lebedev_rule.cc
tools/gencube.h
tools/spectrum.h
calculators/rates.h

**Comment by JensWehner** [comment]
what?

**Comment by JensWehner** [comment]
okay

**Comment by JensWehner** [comment]
I'll take care of it

**Comment by junghans** [comment]
@JensWehner `git grep exit` is your friend! And please merge the fix to stable if possible!
