### ISSUE TITLE
unit_test_espfit, unit_test_orbitals  and unit_test_qmstate fails on ELEP7

### ISSUE THREAD

**Issue by junghans** [votca/xtp#227]
```
21/47 Test #21: unit_test_espfit ........................***Failed    0.02 sec
Running 1 test case...
unknown location(0): fatal error in "esp_charges": std::runtime_error: regex_error
*** 1 failure detected in test suite "espfit_test"
```
and
```
27/47 Test #27: unit_test_orbitals ......................***Failed    0.02 sec
Running 4 test cases...
unknown location(0): fatal error in "densmat_test": std::runtime_error: regex_error
/builddir/build/BUILD/xtp-1.5/src/tests/test_orbitals.cc(69): last checkpoint
unknown location(0): fatal error in "dipole_test": std::runtime_error: regex_error
/builddir/build/BUILD/xtp-1.5/src/tests/test_orbitals.cc(69): last checkpoint
*** 2 failures detected in test suite "orbitals_test"
```
and
```
32/47 Test #32: unit_test_qmstate .......................***Failed    0.02 sec
Running 2 test cases...
unknown location(0): fatal error in "QMState_test": std::runtime_error: regex_error
/builddir/build/BUILD/xtp-1.5/src/tests/test_qmstate.cc(48): last checkpoint
*** 1 failure detected in test suite "qmstate_test"
```

Details [here](https://github.com/votca/xtp/files/2825573/xtp_build.log.txt).

**Comment by junghans** [comment]
On EPEL7, I had to add `-DBOOST_NO_CXX11_SCOPED_ENUMS` to the `CXXFLAGS`, not sure that triggers it.

**Comment by junghans** [comment]
Give me a bit and I provide a dockerfile to test this!

**Comment by junghans** [comment]
Ok, I was able to reproduce this in docker with the following `Dockerfile`:
```Dockerfile
FROM centos:7
RUN yum install -y wget epel-release spectool make
RUN wget https://raw.githubusercontent.com/votca/fedora-copr/master/votca.spec
RUN yum-builddep -y votca.spec
RUN spectool -g votca.spec
RUN rpmbuild --define "_sourcedir $PWD" -ba votca.spec || true
WORKDIR /root/rpmbuild/BUILD/votca-1.5/x86_64-redhat-linux-gnu
```

To Use:

1. Create an empty folder: `mkdir build_folder`
2. Put the above content in a file called `Dockerfile` in `build_folder`
3. `docker build -t votca_debug build_folder` - this will build and at the end some xtp tests will fail.
4. `docker run -it votca_debug /bin/bash` - this will through you directly into the build.

**Comment by junghans** [comment]
@JoshuaSBrown and @jens this persists even with #234 patched in!

**Comment by junghans** [comment]
ping @JensWehner

**Comment by JensWehner** [comment]
Sorry, I did not see the error. I think it is a regex error, we had the same earlier with the compiler versions. It looks a lot like it

**Comment by JensWehner** [comment]
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5

yep compiler version is too low. I thought we bumped the  minimum required gcc to 5.0
