### ISSUE TITLE
Speed up the matrix matrix multiplication using cublas

### ISSUE THREAD

**Issue by felipeZ** [votca/xtp#262]
Move the [eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page) matrix matrix multiplications to [cublas](https://docs.nvidia.com/cuda/cublas/index.html) using a GPU.

**Comment by felipeZ** [comment]
There is a minimal prototype [here](https://github.com/NLESC-JCER/EigenCuda)

**Comment by felipeZ** [comment]
citing [Mark Harris](https://devblogs.nvidia.com/how-optimize-data-transfers-cuda-cc/): 
*You should not over-allocate pinned memory. Doing so can reduce overall system performance because it reduces the amount of physical memory available to the operating system and other programs. How much is too much is difficult to tell in advance, so as with all optimizations, test your applications and the systems they run on for optimal performance parameters.*

**Comment by JensWehner** [comment]
https://github.com/votca/xtp/pull/277
