### ISSUE TITLE
Add Default values to xml

### ISSUE THREAD

**Issue by felipeZ** [votca/xtp#319]
Add back to the XML files in the share folder the default values hardcoded in the code

**Comment by baumeier** [comment]
Let's take a look at the gwbse.xml file now needed, I'll cut out parts and make my comments:

```xml
<gwbse>
        <basisset help="basiset to use">cc-pvtz</basisset>
        <auxbasisset help="auxilliary basiset to use">aux-cc-pvtz</auxbasisset>
```

- It should be possible to get the basis set information from the preceding DFT calculation.
- It could be possible that the DFT calculation has been done without an auxbasis. In that case, we could default to appending aux- in front of the DFT basis name. Depends if the AOBasis is also going to be stored in the hdf5 file or only its name.

```xml
        <ranges help="default: all levels in RPA, 1:2*HOMO in QP and BSE; other options: factor,explicit">explicit</ranges>
        <rpamax help="only needed, if ranges is factor or explicit, number of levels in rpa">71</rpamax>
        <qpmin help="only needed, if ranges is factor or explicit, lowest MO to be used in GW" >0</qpmin>
        <qpmax help="only needed, if ranges is factor or explicit, highest MO to be used in GW" >12</qpmax>
        <bsemin help="only needed, if ranges is factor or explicit, lowest MO to be used in BSE" >0</bsemin>
        <bsemax help="only needed, if ranges is factor or explicit, highest MO to be used in BSE">71</bsemax>
```
This is a bit nasty. Setting `ranges=full` is problematic for evGW due to convergence issues with unoccupied states far away from the gap. My suggestion is to do the following:
- RPA: all
- GW: 0:2(or 3)*nocc
- BSE: all

```xml
        <vxc help="Exchange correlation functional computation for GW">
                <functional help="functional name(s) according to LIBXC">XC_HYB_GGA_XC_PBEH</functional>
                <grid help="grid quality xcoarse,coarse,medium,fine,xfine">medium</grid>
        </vxc>
```
- get functional from the DFT calculation?
- grid: medium

```xml
        <scissor_shift help="preshift unoccupied MOs by a constant for GW calculation" unit="hartree">0.0</scissor_shift>
``` 
- this

```xml
        <mode help="use single short (G0W0) or self-consistent GW (evGW)">evGW</mode>
```
- G0W0

```xml
        <tasks help="tasks to do gw,singlets,triplets or all">gw,singlets</tasks>
```
- this

```xml
        <sigma_integrator help="self-energy correlation integration method: ppm, exact">exact</sigma_integrator>
```
- PPM

```xml
        <eta help="small parameter eta of the Green's function">1e-3</eta>
        <qp_solver help="QP equation solve method: fixedpoint, grid">grid</qp_solver>
        <qp_grid_steps help="number of QP grid points">1001</qp_grid_steps>
        <qp_grid_spacing help="spacing of QP grid points in Ha">0.001</qp_grid_spacing>
``` 
- grid, but the details?

```xml
        <exctotal help="maximum number of BSE states to calculate">30</exctotal>
``` 
- probably good enough

```xml
        <useTDA help="use TDA for BSE default `false`">0</useTDA>
```
- no TDA

```xml
        <ignore_corelevels help="exclude core MO level from calculation on RPA,GW or BSE level, default=no">no</ignore_corelevels>
``` 
- I think this is an option can could actually go away.

```xml
        <eigensolver help="options for BSE eigenvalue decompostion">
                <dodavidson help="use davidson solver">1</dodavidson>
                <davidson_correction help="DPR or OHLSEN">DPR</davidson_correction>
                <davidson_tolerance help="loose,normal,strict">strict</davidson_tolerance>
                <davidson_ortho help="orthogonalisation routine GS or QR">GS</davidson_ortho>
                <davidson_update help=" how large the search space can become min, safe, max">safe</davidson_update>
                <davidson_maxiter help="max iterations">50</davidson_maxiter>
                <domatrixfree help="solve without explicitly setting up BSE matrix, (slower but a lot less memory required">0</domatrixfree>
        </eigensolver>
```
- I suppose this is fine, probably `domatrixfree=1` is safer option? 

```xml
        <gw_sc_max_iterations>50</gw_sc_max_iterations>
        <gw_mixing_order>20</gw_mixing_order>
        <g_sc_max_iterations>100</g_sc_max_iterations>
        <use_Hqp_offdiagonals>false</use_Hqp_offdiagonals>
</gwbse>
```
- Maybe this. mixing order only applied to evGW and `0=plain update`, `1=linear mixing`, and `>1 Anderson mixing`.

Any thoughts @felipeZ @NicoRenaud @JensWehner @gtirimbo @onurcaylak ?

**Comment by JensWehner** [comment]
Why can `ignore_corelevels` go? I agree with the basissets, I think we should actually store the basisset in the hdf5 file. The grid details for the qp solver have sensible defaults, so yeah not necessary.

**Comment by baumeier** [comment]
I was thinking it could go into the defaults for the levels, but probably it *is* better to keep it.

**Comment by baumeier** [comment]
The next question is: do we go back to the XML files in the share folder yes or no? I recall that one of the reasons to go back to XML had to do with the python integration. If we go the ASE route, then the call there is basically a shell call to XTP and no "external" access to the defaults is needed. Or am I misremembering?

**Comment by JensWehner** [comment]
The .xml files also provide the input for the `xtp_ -d CALCNAME` command which prints all options out.

**Comment by JensWehner** [comment]
I have no idea what the python integration concept is, so I cannot comment.

**Comment by felipeZ** [comment]
the **ASE** Calculator class calls directly the binaries from the shell, see [calculator method](https://gitlab.com/ase/ase/-/blob/master/ase/calculators/calculator.py#L871), so it is up to the Subclass of the `Calculator` how to call the binary

**Comment by baumeier** [comment]
So, we *do* go back to the UpdateWithDefaults() function?

**Comment by JensWehner** [comment]
that is unrelated. So the "best" way I think would be to:
 - Remove all C++ hardcoded defaults and replace with explicit checks that the option exists
- Introduce the `UpdateWithDefaults()` at a lower level
- Update the full .xml files with the required `default` arguments
- Hide the full .xml files or add another folder where basic .xml input files for users are stored.

Requires:
- We have to remove the nested .xml files completely.

**Comment by baumeier** [comment]
Hm, so just taking the gwbse.xml file as an example for now (because I think it is as full as it can get):
- we put that one in share
- we define all defaults in that file
- gwbse.cc gets the options from that file
- if there is user option file specified, overwrite the defaults from there

We could basically run gwbse without a user xml file?

**Comment by JensWehner** [comment]
in my idea a gwbse.cc file would not exist anymore. We could say that the dftgwbse.xml file is updated with defaults twice once in dftgwbse.cc and once in gwbse.cc

**Comment by baumeier** [comment]
So that will eliminate the nesting? Then also the DFT options will need to be explicit, right?

**Comment by JensWehner** [comment]
the de-nesting has to be done by hand. What do you mean by explicit?

**Comment by baumeier** [comment]
Something like this:
```xml
<options>
	<dftgwbse help="Electronic Excitations using GW-BSE">


		<!--dftpackage help="Package for DFT ground state">dftpackage.xml</dftpackage-->
		<package>
  			<name>xtp</name>
  			<executable>xtp</executable>
  			<basisset>cc-pvtz</basisset>
  			<auxbasisset>aux-cc-pvtz</auxbasisset>
  			<functional help="functional name(s) according to LIBXC">XC_HYB_GGA_XC_PBEH</functional>
		<!-- PLUS MORE OPTIONS FOR PACKAGE -->
		</package>

		<mode help="Calculator mode: energy or optimize">optimize</mode>
		<reporting>noisy</reporting>
		<archive>system.orb</archive>
		<molecule>votca.xyz</molecule>


		<gwbse_engine>
			<tasks help="guess,input,dft,parse,gwbse">input,dft,parse,gwbse</tasks>
			<dftlog>system_dft.orb</dftlog>
			<mofile>system.orb</mofile>
			<!--gwbse_options>gwbse.xml</gwbse_options-->
			<gwbse>
				<basisset help="basiset to use">cc-pvtz</basisset>
				<auxbasisset help="auxilliary basiset to use">aux-cc-pvtz</auxbasisset>
				<ranges help="default: all levels in RPA, 1:2*HOMO in QP and BSE; other options: factor,explicit">explicit</ranges>
				<rpamax help="only needed, if ranges is factor or explicit, number of levels in rpa">71</rpamax>
				<qpmin help="only needed, if ranges is factor or explicit, lowest MO to be used in GW" >0</qpmin>
				<qpmax help="only needed, if ranges is factor or explicit, highest MO to be used in GW" >12</qpmax>
				<bsemin help="only needed, if ranges is factor or explicit, lowest MO to be used in BSE" >0</bsemin>
				<bsemax help="only needed, if ranges is factor or explicit, highest MO to be used in BSE">71</bsemax>
				<vxc help="Exchange correlation functional computation for GW">
					<functional help="functional name(s) according to LIBXC">XC_HYB_GGA_XC_PBEH</functional>
					<grid help="grid quality xcoarse,coarse,medium,fine,xfine">medium</grid>
				</vxc>
				<scissor_shift help="preshift unoccupied MOs by a constant for GW calculation" unit="hartree">0.0</scissor_shift>
				<mode help="use single short (G0W0) or self-consistent GW (evGW)">evGW</mode>
				<tasks help="tasks to do gw,singlets,triplets or all">gw,singlets</tasks>
				<sigma_integrator help="self-energy correlation integration method: ppm, exact">exact</sigma_integrator>
				<eta help="small parameter eta of the Green's function">1e-3</eta>
				<qp_solver help="QP equation solve method: fixedpoint, grid">grid</qp_solver>
				<qp_grid_steps help="number of QP grid points">1001</qp_grid_steps>
				<qp_grid_spacing help="spacing of QP grid points in Ha">0.001</qp_grid_spacing>
				<exctotal help="maximum number of BSE states to calculate">30</exctotal>
				<useTDA help="use TDA for BSE default `false`">0</useTDA>
				<ignore_corelevels help="exclude core MO level from calculation on RPA,GW or BSE level, default=no">no</ignore_corelevels>
				<eigensolver help="options for BSE eigenvalue decompostion">
					<dodavidson help="use davidson solver">1</dodavidson>
					<davidson_correction help="DPR or OHLSEN">DPR</davidson_correction>
					<davidson_tolerance help="loose,normal,strict">strict</davidson_tolerance>
					<davidson_ortho help="orthogonalisation routine GS or QR">GS</davidson_ortho>
					<davidson_update help=" how large the search space can become min, safe, max">safe</davidson_update>
					<davidson_maxiter help="max iterations">50</davidson_maxiter>
					<domatrixfree help="solve without explicitly setting up BSE matrix, (slower but a lot less memory required">0</domatrixfree>
				</eigensolver>
				<gw_sc_max_iterations>50</gw_sc_max_iterations>
				<gw_mixing_order>20</gw_mixing_order>
				<g_sc_max_iterations>100</g_sc_max_iterations>
				<use_Hqp_offdiagonals>false</use_Hqp_offdiagonals>
			</gwbse>


			<redirect_logger>0</redirect_logger>
		</gwbse_engine>

                                                                      
                <geometry_optimization>
                  <state>s1</state>
                  <optimizer>
                  <method>engrad</method>
                  </optimizer>
                  <forces><method>central</method></forces>
                  <statetracker><filters></filters></statetracker>
                </geometry_optimization>


		
	</dftgwbse>
</options>
```

**Comment by JensWehner** [comment]
yes exactly.

**Comment by baumeier** [comment]
Then we should also make sure that we don't have to double define stuff like `basisset`. Probably moving those options to a higher level and then passing through?

**Comment by JensWehner** [comment]
actually, I think it would be better to not have a basisset option in gwbse.

**Comment by baumeier** [comment]
True. The other nasty thing is the `mofile` and `dftlog`...

**Comment by JensWehner** [comment]
yeah, we have two options in my mind: 
a) use defaults and otherwise leave the option
b) encapsulate the whole logfile thing deeper and hardcode them.

**Comment by baumeier** [comment]
I think we could get the first part of the xyz file name string, and then build the output filenames from there. Basically similar to what other codes do.

**Comment by JensWehner** [comment]
yeah tools::filesystem has the necessary methods.

**Comment by felipeZ** [comment]
Now, we can add the default to the rest of the calculators,
TODO:
 * [ ] eqm
 * [ ] iexcitoncl
 * [ ] iqm
 * [ ] qmmm

**Comment by JensWehner** [comment]
> yeah, we have two options in my mind:
> a) use defaults and otherwise leave the option
> b) encapsulate the whole logfile thing deeper and hardcode them. i.e. replace the input,dft,parse by simply dft, which encapsulated all three parts, then we do not have to care about that anymore.
