### ISSUE TITLE
xjobwriter H-bonds

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#32]
For some QM/MM applications, it is important to include also H-bonded solvent molecules in the QM region. Automatic generation of such a list of segments is desired, but I think it requires additional information about segment-internal bond structure.

**Comment by JensWehner** [comment]
I do not yet fully understand. The qm region could consists of more segments or do you want to specify qmregions in terms of fragments?

**Comment by baumeier** [comment]
Imagine you have a molecule A in solution with solvent molecules B. Typically we make A the QM molecule and B within the defined cutoffs are in MM.
However in some cases it is discussed that the excitations of A are influenced more significantly by some solvent molecules which form H bonds with A. To properly take those into account, they need to be added to the QM region. 
One can identify those molecules with VMD and write the jobs file entry manually at the moment. Making that automatic might be more convenient, particularly for cases with more segments per residue.

**Comment by JensWehner** [comment]
now you can add a cutoff to a segment to include others in the QMRegion https://github.com/votca/xtp/pull/237
