### ISSUE TITLE
dftengine in xqmmm

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#35]
xqmmm uses qmmachine, which is templated to QMPackage. 
To use our dftengine, we could register it as a QMPackage with dummy implementations, e.g. for ParseLogfile() and the like.
Better options?

**Comment by JensWehner** [comment]
Good idea, I did not do it because I was not sure how to handle qmape, otherwise it is the best option.

**Comment by JensWehner** [comment]
This was closed with commit https://github.com/votca/xtp/commit/d4bf03ecbb295d2e470a2b94d7e163eab3cee15a
