### ISSUE TITLE
Duplicated basissets

### ISSUE THREAD

**Issue by junghans** [votca/xtp#384]
On a case-insensitive file-system git cannot checkout `aux-cc-pVTZ.xml`, `aux-def2-SVP.xml`, `cc-pVTZ.xml` and `def2-SVP.xml` as filename with different capitalization exist, e.g. `aux-cc-pVTZ.xml` and `aux-aug-cc-pvtz.xml`.

**Comment by JensWehner** [comment]
@baumeier true which ones do you want to use?
https://github.com/votca/xtp/tree/master/share/basis_sets
