### ISSUE TITLE
Extend BSE active space to include levels < qpmin and > qpmax

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#388]
In some cases, it would be useful to restrict accurate GW corrections to a smaller set of molecular orbitals and include appropriately shifted levels below qpmin and above qpmax in the construction of the BSE.
This can be useful in partiuclar for slowly or hardly converging evGW calculation on the full set of molecular orbitals, and is done in similar fashion in the literature.
@JensWehner pointers to where changes are needed to achieve this are appreciated.

**Comment by JensWehner** [comment]
It is all in the bse_ooerator.cc hqp Part. So you have to extend the quasiparticle hamiltonian and remove the checks in gwbse.cc
