### ISSUE TITLE
Use all the available GPU

### ISSUE THREAD

**Issue by felipeZ** [votca/xtp#397]
Currently, only one GPU is used for the three Center integrals. It would be great if we use all the available GPUs on a given machine.

**Comment by felipeZ** [comment]
See [this post](https://devblogs.nvidia.com/cuda-pro-tip-always-set-current-device-avoid-multithreading-bugs/)

**Comment by JensWehner** [comment]
Is implemented in https://github.com/votca/xtp/pull/601
