### ISSUE TITLE
make a conda recipe for votca xtp

### ISSUE THREAD

**Issue by felipeZ** [votca/xtp#398]
A great way to improve the usability of Votca is to make it easy to install by providing the votca binaries using [conda-forge](https://conda-forge.org/)

**Comment by felipeZ** [comment]
I have created the [template for the conda-forge recipe](https://github.com/votca/staged-recipes), further instructions about how to recreate the recipe can be found [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-recipe-meta-yaml)

**Comment by junghans** [comment]
We already have [spack](https://spack.io/), just use `spack install votca-xtp`.

**Comment by felipeZ** [comment]
I see, thanks! I am closing this issue
