### ISSUE TITLE
Contour integration in complex plane 

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#4]
to replace PPM

**Comment by JensWehner** [comment]
@gtirimbo is this still relevant? Is the implementation done?

**Comment by gtirimbo** [comment]
Still relevant. Implementation done. I can reproduce what you calculate with other methods in XTP but way slowly. 'Optimization' is needed. Improvements should come  the new features that @baumeier made. I should merge master into this branch and test it. 

 Btw @wscharpach was assigned to this part.

**Comment by JensWehner** [comment]
okay nice.

**Comment by JensWehner** [comment]
Which new features? Btw.?

**Comment by baumeier** [comment]
I think @gtirimbo refers to the way of restricting the explicit GW corrections to a smaller set of levels.

**Comment by JensWehner** [comment]
ahh okay.
