### ISSUE TITLE
Option to use offdiagonal elements of Hqp in BSE

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#402]
Including the symmetrized offdiagonal elements of the quasiparticle Hamiltonian in the BSE can lead to spurious effects, such as discontinuities in excitation energies as a function of bond length in diatomic molecules. 
Use of these offdiagonal should be optional.

**Comment by JensWehner** [comment]
my gut feeling: 

when we use Hqp_diag we are basically doing everything in the MO basis

if we use the offdiag of Hqp we could also just use the eigenvalues and eigenvectors of Hqp to build H_BSE, how would we have to modify H_d and H_x then?

**Comment by baumeier** [comment]
There is no reference, it is an observation. The underlying issue is the unresolved question how to deal with the fact that including the offdiagonal elements makes Hqp not symmetric anymore. AFAIK the other codes ignore it, there is only https://pubs.acs.org/doi/10.1021/acs.jctc.5b00394 in which it has been explored recently (and where the effects where deemed to be small compared to an approximate update of the eigenvalues). In Fig.2 one can clearly see that Hqp is not symmetric, and eigenvalues are not guaranteed to be real and that should cause havoc in the current way the BSE is implemented. 

For the moment, I would like to have the option to ignore the offdiagonals or take them into account in the symmetric form as we do now. The rest takes a major investigation, I think. PR incoming.
