### ISSUE TITLE
Extend the choices option

### ISSUE THREAD

**Issue by JensWehner** [votca/xtp#442]
at the moment the `choices` tag accepts, `bool` `int` `int+` and `float` `float+` and a list of choices, from which you can take one, e.g. `choices=a,b,c`, which means either `a` `b` or `c` in some situations we do not want a single choice but also allow combinations e.g `a,b` or `a,c` or even `a,b,c` as an allowed choice. 

How do we separate the two?
Example is `input,parse,dft,gwbse` in dftgwbse.

we could say that `choice=a,b,c` means choose one of them
whereas `choice=[a,b,c]` means choose any combination of a,b,c

**Comment by felipeZ** [comment]
See also the [tools extension](https://github.com/votca/tools/pull/241)
