### ISSUE TITLE
votca-xtp in Debian

### ISSUE THREAD

**Issue by junghans** [votca/xtp#449]
In progress https://ftp-master.debian.org/new/votca-xtp_1.6-1.html and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921202

**Comment by JensWehner** [comment]
@junghans still relevant?

**Comment by junghans** [comment]
Yeah, still in progress

**Comment by junghans** [comment]
Finally done a week ago: https://packages.debian.org/sid/votca-xtp

@baumeier might be worth a tweet ;-)
