### ISSUE TITLE
libxc and Orca functional names

### ISSUE THREAD

**Issue by felipeZ** [votca/xtp#461]
## Description
For running a DFT-GWBSE calculations the user needs to provide a **XC** functional but the problem is that [Orca uses its own functional names](https://sites.google.com/site/orcainputlibrary/dft) and for the GWBSE calculations **XTP** follows the **libXC**  name convention. So, the current configuration breaks if we try to use Orca and then perform a GWBSE calculation

## Solutions
* **Use libXC name convention**: Create and maintain a map from XC  to Orca functional names.
* **Use Orca name convention**: Since Orca 4.2 It is printed in the Orca output the name in the libXC convention, so we can parse and use it.

Since we are also planning to integrate [PySCF](https://sunqm.github.io/pyscf/) and it uses **libXC** then option 1 since more suitable.

@baumeier @JensWehner  any thoughts about this?

**Comment by JensWehner** [comment]
I prefer option 1.

**Comment by baumeier** [comment]
Option 1.
