### ISSUE TITLE
Support for different ECPs

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#464]
The standard `def2` series of basis sets comes by default also with definition for 4th row elements, strictly to be used with the `def2-ecp` definitions. 
XTP can write the input for `orca` but currently does not support the use in the internal `dftengine`. 

Since adding this to the internal implementation is not a priority at the moment, how can we make sure that the user does not use the `def2-ecp` and `xtpdft` combination?

**Comment by JensWehner** [comment]
What is the problem with the internal implementation?

**Comment by baumeier** [comment]
AFAIK, we don't account for explicit local parts.

**Comment by JensWehner** [comment]
Is it difficult to add?

**Comment by baumeier** [comment]
I think they are basically integrals of the type 

<alpha | r^2 exp(-a*r^2) | beta>

so like the non-local parts we have right now without the angular momentum projectors. 

However, this all goes together with high order functions in the basis set, and I thought our current ECP implementation also is not going that far?

**Comment by JensWehner** [comment]
it goes up to g shells with f as the highest ecp
