### ISSUE TITLE
unit_test_sigma_ppm fails on F31

### ISSUE THREAD

**Issue by junghans** [votca/xtp#469]
```
226/254 Test #233: unit_test_sigma_ppm ................................***Failed    0.02 sec
Running 1 test case...
unknown location(0): fatal error: in "sigma_test/sigma_full": memory access violation at address: 0x00000000: no mapping at fault address
../xtp/src/tests/test_sigma_ppm.cc(254): last checkpoint

*** 1 failure is detected in the test module "sigma_test"
```

Details here: https://github.com/votca/votca/pull/333/checks?check_run_id=776460163

**Comment by JensWehner** [comment]
yeah that is again an openmp problem with the custom reductions.... argh

**Comment by JensWehner** [comment]
it finds an openmp version that is high enough.

**Comment by JensWehner** [comment]
I have no idea how to fix this apart from reverting https://github.com/votca/xtp/pull/466

**Comment by JensWehner** [comment]
actually it is a bug  in clang-9 and lower. https://bugs.llvm.org/show_bug.cgi?id=44134

@junghans what would you do?

**Comment by junghans** [comment]
Well, I guess we will have to disable building with OpenMP for clang-9.
