### ISSUE TITLE
Use the N logN grid NN search instead of N^2

### ISSUE THREAD

**Issue by JensWehner** [votca/xtp#48]
CSG has an implementation. Maybe Christoph some thoughts on it?.

Cheers Jens

**Comment by junghans** [comment]
Yes, you can use `votca::csg::NBListGrid`, see: http://votca.github.io/doxygen/classvotca_1_1csg_1_1NBListGrid.html

**Comment by baumeier** [comment]
@JensWehner still of interest? If so, where?

**Comment by JensWehner** [comment]
I wanted to use it for the neighborlist determination, but it was never really necessary

**Comment by baumeier** [comment]
Then let's drop it.
