### ISSUE TITLE
NOSCF option for iqm in internal and external DFT

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#481]
Introduce single step SCF step options for use in noscf transfer integral calculation in iqm. 

- [x] For orca, the input writing of the predefined SCF option needs to be adapted. 
- [ ] Since orca has no NOSCF keyword, automatically insert the complete `<SCF>` and `<output>` blocks.
- [ ] Check what needs to be defined for internal `dftengine`

**Comment by baumeier** [comment]
@JensWehner @felipeZ Is the keyword `<convergence_tightness>` used in `xtpdft`? Are the four/five convergence levels predefined there somewhere too, or is it just used for `orca` at the moment?

**Comment by felipeZ** [comment]
> @JensWehner @felipeZ Is the keyword `<convergence_tightness>` used in `xtpdft`? Are the four/five convergence levels predefined there somewhere too, or is it just used for `orca` at the moment?
@baumeier the keyword is only used for Orca at the moment

**Comment by baumeier** [comment]
Should we not do the same in `xftdft`: define some translations of the keyword to settings?

**Comment by JensWehner** [comment]
As a physics question is noscf actually a good idea, why not let the calculation converge to a very low tolerance?

**Comment by baumeier** [comment]
Ideally that is the same. Having a predefined setting keyword might just be
easier. Also for `orca` it is a combination of a few low tolerance
settings, that seem a bit nasty to leave the user to set.

**Comment by baumeier** [comment]
OF course only as long a merged guess is requested/present.

**Comment by JensWehner** [comment]
I agree and a low tolerance options is certainly helpful. I still do not like the noSCF option, because you risk treating different pairs unequally depending on how much they change in the first iteration.

**Comment by baumeier** [comment]
Of course NoSCF is an approximation and it is up to the user to either do it or not. However, we -and others - have published several papers with exactly that procedure and I do not want to have that possibility removed.

**Comment by baumeier** [comment]
For the record, this is what needs to be inserted in `orca`: 

```
 <scf> TolE 1e-2
                ConvCheckMode 1
                Guess MORead
                MOInp "dimer.gbw"</scf>

                <output> Print [P_Mayer] 0
                Print [P_Mulliken] 0
                Print [P_Loewdin] 0</output>
```

**Comment by baumeier** [comment]
@felipeZ How do we best inset the `scf` and `output` options above if `convergence_tightness` is set to none?

**Comment by felipeZ** [comment]
@baumeier  I have done a couple of changes in #470:
* I have removed the default `SCF` for orca.
* If the user doesn't define a `SCF` section then the `convergence_tightness` variable is going to be use.
* If the user define the a `SCF` section then no extra `SCF` keywords are added by default

So, for the keywords that you mention about you will need to provide an input like:
```xml
<dftpackage>
  <package>
  <name help="Name of the DFT package" default="xtp" choices="xtp,orca">orca</name>
  <executable>/home/user/local/orca_4_0_1_2/orca</executable>
  <orca>
  <scf>
   TolE 1e-2
  </scf>
  <output>  -->
    Print [P_Mayer] 0
    Print [P_Mulliken] 0
    Print [P_Loewdin] 0
  </output>
 </orca>
 </package>
</dftpackage>

```

**Comment by baumeier** [comment]
Did you check my NOSCF branch?

**Comment by felipeZ** [comment]
Not, I have done the changes in the branch [issue_461](https://github.com/votca/xtp/tree/issue_461) because there is were I implemented the changes for translating the LibXC names into Orca

**Comment by baumeier** [comment]
@felipeZ Are you sure it will do the right thing like this? The newlines might not be recognized everything in `output` for example will end up in a single line.

Another question then: I sense some reluctance in going for predefined settings, such as noscf. I can live with this but then we need to add the info about what to do for the packages (like adding the above) somewhere.

**Comment by JensWehner** [comment]
I like the idea of predined settings, but we have to store them in a sensible and open way somewhere.

**Comment by baumeier** [comment]
I am open to suggestions.

**Comment by felipeZ** [comment]
@baumeier About the new lines, I just run a DFTGWBSE calculation using the following input:
```xml
  <dftgwbse help="Compute electronic excitations using GW-BSE">
    <optimize help="Perform a molecular geometry optimization" default="false" choices="bool" />
    <basisset help="Basis set for MOs">ubecppol</basisset>
    <auxbasisset help="Auxiliary basis set for RI">aux-ubecppol</auxbasisset>
    <functional help="Functional name(s) according to LIBXC" default="XC_HYB_GGA_XC_PBEH" />
    <dftpackage>
      <package>
        <name help="Name of the DFT package" default="xtp" choices="xtp,orca">orca</name>
        <executable>/home/felipe/local/orca_4_0_1_2/orca</executable>
        <orca>
          <scf>                                                                                                                                                                                            
TolE 1e-2                                                                                                                                                                                                  
Guess MORead                                                                                                                                                                                               
          </scf>
          <output>                                                                                                                                                                                         
Print [P_Mayer] 0                                                                                                                                                                                          
Print [P_Mulliken] 0                                                                                                                                                                                       
Print [P_Loewdin] 0                                                                                                                                                                                        
          </output>
        </orca>
      </package>
    </dftpackage>
...
```
It produces the following orca input:
```xml
%scf
TolE 1e-2
Guess MORead
end
%output
Print [P_Mayer] 0
Print [P_Mulliken] 0
Print [P_Loewdin] 0
end
! DFT PBE0 
```

About the predefined settings, I am in favor of them because most of the users are going to run a limited set of options. Therefore predefined settings make their lives easier and advance users can always overwrite the defaults

**Comment by baumeier** [comment]
@felipeZ OK, then it is perfect.

**Comment by JensWehner** [comment]
Can we not put them into the qmpackages.xml?

**Comment by felipeZ** [comment]
> Can we not put them into the qmpackages.xml?

Yes, we can and I would advice in going in that direction.

@baumeier  @JensWehner  We should also need to take a decision about the interaction between the defaults and the user input:

### Current implementation
* The orca class write whatever is in the defaults
* If the user provides an input it **throws away** the defaults and write the user input

### Alternative behaviour
* If there are no user input use the defaults as above
* If the user provides some input  it would **merge** the user input with the defaults

**Comment by JensWehner** [comment]
how would the merge look like?

**Comment by felipeZ** [comment]
> how would the merge look like?

Imaging that the defaults are:
```xml
<orca>
 <scf>
TolE 1e-2                                                                                                                                                                                                  
</scf>
</orca>
```
And the user input is:
```xml
<orca>
 <output>                                                                                                                                                                                         
Print [P_Mayer] 0                                                                                                                                                                                          
Print [P_Mulliken] 0                                                                                                                                                                                       
Print [P_Loewdin] 0                                                                                                                                                                                        
 </output>
</orca>
```
Then the resulting input will be:
```xml
<orca>
  <scf>
TolE 1e-2                                                                                                                                                                                                  
</scf>
  <output>                                                                                                                                                                                         
Print [P_Mayer] 0                                                                                                                                                                                          
Print [P_Mulliken] 0                                                                                                                                                                                        
Print [P_Loewdin] 0                                                                                                                                                                                       </output>
</orca>
```

### behavior
* If the `defaults` doesn't have a keyword that is present in the `user input` (e.g. `scf`) then add it.
* If both `defaults` and `user input` has the same keyword (e.g. `scf`) throw away the defaults and keep the `user input`
