### ISSUE TITLE
Print all found quasiparticle energies and QP weights

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#492]
The QP equations in the GW step may have several possible solutions. Currently the one with the largest spectral weight is chose as "THE" solution but it would be informative to also - maybe in verbose mode - also print the discarded solutions and their weights.

**Comment by JensWehner** [comment]
How can I help?

**Comment by baumeier** [comment]
You could either do it :) or let me know where this is exactly and if this already kept track of in some form or not

**Comment by JensWehner** [comment]
I am going to have a look on wednesday.
