### ISSUE TITLE
Orca pointcharges are not generated properly

### ISSUE THREAD

**Issue by felipeZ** [votca/xtp#504]
## Problem
During a QMMM calculation charges can be given to orca for reading using the filename `background.crg`.  But the method in charge of doing so 
 ```cc
void Orca::WriteChargeOption()
```
Fails to properly write that in the orca input.

## Solution 
Fix the `WriteChargeOption` method

**Comment by JensWehner** [comment]
?

**Comment by felipeZ** [comment]
There is a bug on the method that writes the pointcharges in hte Orca input

**Comment by JensWehner** [comment]
I thought that is just the string

**Comment by baumeier** [comment]
`void Orca::WriteChargeOption()` is supposed to put the string in the *inputfile* that it should read the charges from the additional charges file
`Orca::WriteBackgroundCharges()` is supposed to actually write charges file

Which one is now not working?

**Comment by felipeZ** [comment]
`void Orca::WriteChargeOption()` 

> `void Orca::WriteChargeOption()` is supposed to put the string in the _inputfile_ that it should read the charges from the additional charges file
> `Orca::WriteBackgroundCharges()` is supposed to actually write charges file
> 
> Which one is now not working?

`void Orca::WriteChargeOption()` is not working properly
