### ISSUE TITLE
Getting Rid of combined shells

### ISSUE THREAD

**Issue by JensWehner** [votca/xtp#538]
At the Moment VOTCA supports shells of the type "SPD" or "PDFG", 

I want to remove that feature and only allow shells of the type "S" "P" "D" etc... .

Reasons:

a) Most basissets we use do not have that kind of shells
b) Most basissets are contracted and it allows us to optimize that path a lot more. 
c) It makes implementing new features a lot easier because this special case does not have to be treated anymore. Easier for new comers
d) Libint and Orca do no have it and even gaussian only supports SP shells, for which the performance gain is small.
e) We could indicate shells not by a `char` or a `string` but simply by `L` which is a lot nicer. 

Cons:

It would hurt the most for aux-basissets that were constructed with our `make_auxbasis` scripts, but even there I think the performance gain from maybe switching to libint at some point might be bigger. 

In general as we store integrals in memory at the time, this whole thing will not be critical. 

@baumeier any thoughts?
@felipeZ thoughts?
@rubengerritsen might be helpful for your stuff as well

Possible implementation workflow:
Basisset splits up combined shells when it reads them in, into single shells. This is fully backward compatible.
From there we can bit by bit remove all other places where combined shells are used.

**Comment by felipeZ** [comment]
I think that if we plan to move to `libint` in the future it is a good think to do

**Comment by baumeier** [comment]
No objections.

**Comment by JensWehner** [comment]
Actually our whole .xml basisset thing is really dangerous, because we assume that the shells are ordered in the xml,, while the xml format does not guarantee it. So basically every shell should have an index.

i.e. 
<element>
<shell "number"=0>
...
</shell>
<shell "number"=1>
...
</shell>
</element>
