### ISSUE TITLE
Refactor correction in RPA

### ISSUE THREAD

**Issue by JensWehner** [votca/xtp#557]
This part has to be refactored in a function and maybe add a bit of documentation of what it does

https://github.com/votca/xtp/blob/eea8e1499ef8bd8474908a4ed50e9b4fdc968474/src/libxtp/gwbse/rpa.cc#L40-L54

**Comment by JensWehner** [comment]
@baumeier ping :)

**Comment by baumeier** [comment]
ping me again in 4 weeks

**Comment by JensWehner** [comment]
@baumeier ping

**Comment by JensWehner** [comment]
@baumeier ping

**Comment by baumeier** [comment]
working on it
