### ISSUE TITLE
ECP integrals via library

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#567]
Replace our implementation by https://github.com/robashaw/libecpint ?

**Comment by rubengerritsen** [comment]
I had already discussed it a bit with @JensWehner, he saw at least the following two problems for now

- Building it is still a bit of a pain so we have to figure out how to manage the dependencies and
- It returns Cartesian functions elements so we have to rework our transformation class aotransform.

So we will pick it up at some point, but focus firstly on the libint integration.

**Comment by JensWehner** [comment]
Building is a bit of a pain, because the dynamic library build does not work with their tests, I am also not sure how much we can afford the compilation time with regard to the CI. This library is a lot further away from being part of a distribution than libint and it is also a lot less useful. In Principle we should use it because aoecp is a pain

**Comment by baumeier** [comment]
>  less useful. In Principle we should use it because aoecp is a pain

That does sound useful, then. ;)

**Comment by JensWehner** [comment]
Yes I agree, but the pain to usefulness ratio is worse than for libint.

**Comment by baumeier** [comment]
How about an optional build? We need the ECP Integral "only" for our internal DFT, and that has limited use anyways: 
- it turns out that def2-svp with ignored core levels is giving basically identical results for ECP+"ubecpol"
- ECPs will be important for molecules with transition metals and such, but then if somebody needs it, it can still be done by orca

**Comment by baumeier** [comment]
> Yes I agree, but the pain to usefulness ratio is worse than for libint.

Of course but I didn't think that this was related in any way to libint. It's an extra (for later).

**Comment by junghans** [comment]
Let me have a look at libecpint to see how hard it would be to make a package out of it.

**Comment by junghans** [comment]
I talked to @robashaw and made it packageable.

Gentoo: https://github.com/gentoo/gentoo/commit/ff77abc98e9ddc1765499b896079c176f9e083b0
Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1884943

**Comment by baumeier** [comment]
That was fast. Very nice.

**Comment by junghans** [comment]
https://ftp-master.debian.org/new/libecpint_1.0.2-1.html

**Comment by JensWehner** [comment]
link is dead

**Comment by junghans** [comment]
> link is dead

That means it made it into Debian: https://packages.debian.org/sid/libecpint-dev, next Ubuntu release should have it, too.

**Comment by junghans** [comment]
@JensWehner libecpint will part of Ubuntu 21.04, https://launchpad.net/ubuntu/+source/libecpint/1.0.2-1

**Comment by junghans** [comment]
@mbanck, small nitpick, libecpint-dev should depend on libpugixml-dev, I think dpkg could not determine the deps automatically as it is a static lib.

Also the patch from https://github.com/robashaw/libecpint/pull/16 would be nice.

**Comment by junghans** [comment]
Will need https://github.com/robashaw/libecpint/pull/26 as well.

**Comment by junghans** [comment]
@mbanck could you make the next build of libecpint incl. a shared library (`-DBUILD_SHARED_LIBS=ON`)? Alternatively the static build of libecpint needs to be depend on `libpugixml`.

**Comment by mbanck** [comment]
> @mbanck could you make the next build of libecpint incl. a shared library (`-DBUILD_SHARED_LIBS=ON`)? 

Does it have a stable interface?

> Alternatively the static build of libecpint needs to be depend on `libpugixml`.

I've just uploaded `libecpint_1.0.4-2` trying to do that, can you check whether that's good?

**Comment by junghans** [comment]
> > @mbanck could you make the next build of libecpint incl. a shared library (`-DBUILD_SHARED_LIBS=ON`)?
> 
> Does it have a stable interface?

I think so, but @robashaw, any comments?

**Comment by robashaw** [comment]
The interface will not be changing any time soon as far as I’m concerned.

**Comment by junghans** [comment]
> The interface will not be changing any time soon as far as I’m concerned.

@mbanck could bump the package to provide a shared library as well?

**Comment by JensWehner** [comment]
can we wait till the recent PRs are merged?

**Comment by junghans** [comment]
> can we wait till the recent PRs are merged?

Static or shared don’t really change anything for us. CMake already does everything.
