### ISSUE TITLE
Gencube state option choices

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#578]
In the default `gencube.xml` the possible choices for the state to plot are just
```
<state help="State to generate cube file for" default="N" choices="N"/>
```
and the calculator only allows for cube files of the ground state.

Unless we have a way to tell `choices` that they should be any combination ground, QP, and BSE states that we can compute, I suggest to remove the `choices` here.

**Comment by JensWehner** [comment]
yes good point.
