### ISSUE TITLE
Gencube doesn't like QMMM hdf5 files

### ISSUE THREAD

**Issue by gtirimbo** [votca/xtp#580]
Is it possible to make a cube file starting from a QMMM calculation?
It seems gencube digests only hdf5 files generated for simple QM calculations. QMMM ones are different from the 'simple' QM ones. Thus gencube fails.

Am I missing something?

**Comment by JensWehner** [comment]
There was the idea flying around at some point to write a python script to extract an .orb file from a qmmm checkpoint file.

**Comment by baumeier** [comment]
Isn't that somehow unintuitive for a user? What are the extraction options in a qmmm checkpoint file compared to a regular orb?

**Comment by JensWehner** [comment]
What would you like to have?

**Comment by JensWehner** [comment]
In principle checkpoint files can have more than 1 qmregion, so you would have to ask the user which one they want, I would make that a separate tool.

**Comment by JensWehner** [comment]
and if it is in python I do not have to do it. :+1:

**Comment by baumeier** [comment]
I feel that everything we do with python now(ish) is somewhat uncontrolled. I mean we have all sorts of standard for C++, CI, tests etc. and nothing for python. How do we keep track of having to make changes to a python tool like this if, for some reason, the checkpoint/orb structure changes?

**Comment by JensWehner** [comment]
@junghans @felipeZ do you have any experience testing the python code via CMake?

**Comment by JensWehner** [comment]
@baumeier what kind of functionality do you want?

**Comment by felipeZ** [comment]
> @junghans @felipeZ do you have any experience testing the python code via CMake?

Testing python only requires to install a dependency [pytest](https://docs.pytest.org/en/stable/) and then you can run the tests with the following shell command:
```bash
pytest path_to_tests
```

**Comment by baumeier** [comment]
@JensWehner for `gencube` or the python stuff in general? Maybe we should move the latter discussion to a separate issue.

**Comment by JensWehner** [comment]
for the gencube stuff.

**Comment by baumeier** [comment]
I’m not sure what is possible. Could one add another option for region by
which the code knows it’s a orb or qmmm hdf?

**Comment by JensWehner** [comment]
I do not think it is a good idea to add this gencube.

**Comment by JensWehner** [comment]
Because extracting a subpart is a generally useful feature for example ecp fits etc...

**Comment by baumeier** [comment]
I suppose that meant esp fit?

**Comment by baumeier** [comment]
Well, then let us see how we can make at least some sort of python framework so that all tools we design do not look like the C++ code from 6 years ago.

**Comment by gtirimbo** [comment]
I have written a simple python script that does this conversion from QMMM orb file to a QM-like orb file. Where should I put it?

**Comment by JensWehner** [comment]
Cool, it should go here https://github.com/votca/xtp/tree/master/scripts

**Comment by gtirimbo** [comment]
This issue can be close due to the approved pull request
