### ISSUE TITLE
Auto Generate Segments.xml File

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/xtp#59]
It would be nice to automatically generate this file, as it is a major pain for the user. Especially as the molecular systems become more complex. A safe first step would be to consider each molecule a fully conjugated segment. In terms of determining the rigid fragments this can be achieved by looking for rings, fused rings or single carbon chains of ~ 2 atoms. 

![image](https://user-images.githubusercontent.com/4664476/33232756-ccc346be-d1c8-11e7-9fd9-e1174c1e9d48.png)
![image](https://user-images.githubusercontent.com/4664476/33232757-d6119c20-d1c8-11e7-8fc0-ea0ed3bd369c.png)
![image](https://user-images.githubusercontent.com/4664476/33232760-dedc3900-d1c8-11e7-99c9-5b9417949f66.png)

Determination of which combination of rigid fragments constitutes a single conjugated segment... is a little more complicated. One first step would be to look at the charge transfer integral between each rigid fragment. We would have to look at the charge transfer integrals of all the energy relevant energy levels which may not just consist of the HOMO.

**Comment by JoshuaSBrown** [comment]
One difficulty in accomplishing this is determining which class is the most ideal for putting the methods. Having a class that is a child of the topology class would be ideal this would ensure that you have the information of the whole system. However, we also want to avoid duplicating code and it seems that there are already molecule, segment and fragment classes.

**Comment by JoshuaSBrown** [comment]
# Approach to problem 
1. Migration of relevant methods to XTP with testing in XTP -> migration branch
2. Remove dependencies to old repo and replace with XTP dependencies -> linking branch
3. Refactor branch clear up code/consolidate and move structural components to csg -> refactor branch
4. Add graph library type functionality to tools -> graph branch
5. Automate segment and fragment detection -> ?

**Comment by JoshuaSBrown** [comment]
Issues raised by @junghans and @JensWehner in issue #89 will be addressed in Step 3 of the above shown approach.

**Comment by JoshuaSBrown** [comment]
First step done:
https://github.com/votca/tools/pull/44

**Comment by JoshuaSBrown** [comment]
It turns out after testing it does not make sense to use conjugated segments. Breaking up a molecule at arbitrary points does not really work nor is it a systematic approach. Fragments will instead be determined by looking for the rigid components in a molecule and breaking them up accordingly. If we want to use the existing structure we could simply make the whole molecule a conjugated segment, but it would probably be better to simply remove the concept and start with molecule and fragment classes based on the csg bead header file. 

I'm looking at implementing these changes in the xtp_map file with some command like:

    xtp_map --auto-gen-xml 

where it takes one of the topology files as input. @baumeier thoughts?

**Comment by JoshuaSBrown** [comment]
Thus it begins: https://github.com/votca/xtp/tree/feature-automate-system.xml-mapping

**Comment by JoshuaSBrown** [comment]
[ ] - Automatically generate the map.xml file this is not the same as the system.xml file 

Typically xtp_map is run as

    xtp_map -t topol.tpr -c traj.xtc -s map.xml -f state.sql

We would like to replace the `-s map.xml` with a `-auto-gen-map.xml`. There is a slight problem in the internal configuration of xtp_map as it does not follow the same structure as xtp_run xtp_tools and xtp_parallel as all of these exhibit a more modular design which uses calculators.

**Comment by baumeier** [comment]
I think some of this is in a python tool now.
