### ISSUE TITLE
Libint on Ubuntu only supports L=4

### ISSUE THREAD

**Issue by JensWehner** [votca/xtp#608]
Whereas fedora, opensuse and gentoo packages support up to L=6

So updating the ubuntu package would be nice.

**Comment by junghans** [comment]
@mbanck is that something we could add in the debian package?

**Comment by junghans** [comment]
ping @mbanck

**Comment by mbanck** [comment]
Do you have patch, or the `configure` options that are required?

**Comment by JensWehner** [comment]
We build our local version with `--disable-shared --with-pic --enable-eri2 --enable-eri3 --with-max-am=6`

**Comment by junghans** [comment]
Here are fedora’s configure options: https://src.fedoraproject.org/rpms/libint2/blob/master/f/generate-sources.sh#_45

**Comment by mbanck** [comment]
Hrm, so `--enable-eri2` is the same as `--enable-eri2=0` from looking at `configure.ac`, or what would it correspond to, seeing that Fedora seems to do `--enable-eri2=2` (and lot of others)?

**Comment by JensWehner** [comment]
the number should indicate which derivatives are provided for that type of integral

**Comment by mbanck** [comment]
So what's the real-world benefit in going from 4 to 6, seeing how it blows up the build time (and likely library size) by a lot? What kind of computations/simulations will be possible that are currently not?

**Comment by JensWehner** [comment]
So in quantum chemistry basisfunctions are labelled according to their angular momentum. Typically basisfunctions for light elements go up to g(l=4) functions, for heavier elements (3rd row+) higher functions are used. Also often auxiliary basissets are used which routinely go up to i(l=6). Also the derivatives of basisfunctions are used a lot for geometry optimisations of molecules. So the current debian/ubuntu config is basically only useful for unittesting and toy systems. The fedora config can be used in most production settings. 

Also see https://github.com/evaleev/libint/issues/190

**Comment by mbanck** [comment]
I've uploaded libint2 with `l=5` for now, let's see whether the autobuilders cope, I'll bump it to 6 if there's no issues.

**Comment by mbanck** [comment]
I've bumped it to `l=6` now, and the autobuilders have been building it for 11 hours and counting.

**Comment by JensWehner** [comment]
I am starting to see your point.
