### ISSUE TITLE
Hessian and eigenmodes

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#61]
Numerical second derivatives, determination of harmonic modes, IR intensities?

**Comment by pmadhikar** [comment]
Papers with the mode tracking technique expained: 
http://onlinelibrary.wiley.com/doi/10.1002/jcc.20988/full   (QM/MM)
http://aip.scitation.org/doi/abs/10.1063/1.1523908     (Breathing modes of CNTs)
http://www.sciencedirect.com/science/article/pii/0021999175900650   (The davidson algorithm for solving for certain eigen frequencies)

**Comment by baumeier** [comment]
In PyVOTCA
