### ISSUE TITLE
Densityanalysis calculator options

### ISSUE THREAD

**Issue by baumeier** [votca/xtp#627]
Options for the `xtp_tools` calculator `densityanalysis` are messed up, in particular what is passed to the `gyration` object, as it works only for a (non-existing) default like this

```
<?xml version="1.0"?>
<options>
        <densityanalysis>
<density2gyration>
  <density2gyration help="Determine centroid and gyration tensor of electronic density" section="sec:overlap">
          <state help="Sate to analyse" default="s1">s3</state>
    <difference_to_groundstate help="compare to the ground state" default="true" choices="bool"/>
  </density2gyration>
</density2gyration>
  </densityanalysis>
</options>
```

Note the double `density2gyration`.

**Comment by JensWehner** [comment]
uih okay. Can you upload a small example?

**Comment by baumeier** [comment]
What exactly are you interested in seeing? The tool works on any orbfile with BSE info.
