### ISSUE TITLE
Allow votca to write aux basissets to ORCA and gaussian

### ISSUE THREAD

**Issue by JensWehner** [votca/xtp#66]
https://sites.google.com/site/orcainputlibrary/basis-sets

http://users.etown.edu/h/hoffmang/Manuals/g09ur/k_gen.htm

This allows to use density fitting with even our aux basissets.

**Comment by baumeier** [comment]
Orca does this already.

**Comment by JensWehner** [comment]
ohh yes I saw it. Gaussian can do the same.

**Comment by baumeier** [comment]
No way to test. Do you still want to keep this open?

**Comment by baumeier** [comment]
Assume no. Can be revisited by anyone planning to use and has access to Gaussian in the future.
