### ISSUE TITLE
clean and fix scripts

### ISSUE THREAD

**Issue by felipeZ** [votca/xtp#668]
## Proposed changes
* Remove unused scripts
* Clean and remove Python2 syntax
* Remove `make_auxbasis` script
* Improve readability

**Comment by JensWehner** [comment]
nice.

**Comment by JensWehner** [comment]
can we move some stuff into a common package and also include https://github.com/votca/xtp/pull/535 into it?

**Comment by felipeZ** [comment]
I think it is a good idea if we move them to PyVOTCA.What do you think @baumeier ?

**Comment by junghans** [comment]
If we move the scripts in the other package, we need to find a way to re-add the document back to the website.

**Comment by felipeZ** [comment]
I think that in that case we should keep the scripts in this repo then
