### ISSUE TITLE
unit_test_sigma_cda takes 5+ hrs

### ISSUE THREAD

**Issue by junghans** [votca/xtp#687]
from: https://github.com/votca/votca/runs/1981586817?check_suite_focus=true, saw this 3 times already in the CI.

**Comment by JensWehner** [comment]
I guess that is somehow related to the crashes on fedora as well?

**Comment by JensWehner** [comment]
is it always on fedora?

**Comment by JensWehner** [comment]
Three times in which time frame?

**Comment by junghans** [comment]
Within the last week. If I recall correctly it was always fedora.

**Comment by JensWehner** [comment]
I tried recently so far I have not been able to reproduce the issue :(

**Comment by JensWehner** [comment]
@junghans has this happened again?

**Comment by junghans** [comment]
Not for a long time!
