### ISSUE TITLE
Create run time automated testing

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/xtp#71]
Figure out how to get automated run_time testing working through github.

**Comment by junghans** [comment]
Just add a test to cmake like in https://github.com/votca/xtp/blob/master/src/tools/CMakeLists.txt#L26 then Travis will run it automatically.

**Comment by JoshuaSBrown** [comment]
This has been implemented. Here: 
https://github.com/votca/xtp/commit/ea6c801cdfe19a4792e5c36cb42075824485b908
