### ISSUE TITLE
Periodic charge assignment is not trully periodic

### ISSUE THREAD

**Issue by zetadin** [votca/xtp#74]
In [periodic_integration branch](/votca/xtp/tree/periodic_integration) fitting charges to periodic potentials only takes into account the contribution from the nearest images to each point, and not long range interactions. Need to implement Ewald summation [here](/votca/xtp/blob/periodic_integration/src/libxtp/bulkesp.cc) too.

**Comment by baumeier** [comment]
Is this still an issue?

**Comment by JensWehner** [comment]
closed to outdated
